package integration.connector;

class DefinitionStatements {

    static final String PHYSICAL_MODEL = "CREATE TABLE Paziente (ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), Nome char(30) NOT NULL, Cognome char(30) NOT NULL, Data date NOT NULL, PRIMARY KEY (ID));\n" +
            "CREATE TABLE Intervento (ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), Citta char(30) NOT NULL, CAP char(30) NOT NULL, Indirizzo char(50) NOT NULL, Data date NOT NULL, Ora time NOT NULL, PazienteID integer NOT NULL, InfermiereID integer NOT NULL, PRIMARY KEY (ID));\n" +
            "CREATE TABLE Cellulare (Numero char(20) NOT NULL, PazienteID integer NOT NULL, PRIMARY KEY (Numero, PazienteID));\n" +
            "CREATE TABLE Infermiere (ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), Nome char(30) NOT NULL, Cognome char(30) NOT NULL, PRIMARY KEY (ID));\n" +
            "CREATE TABLE Operazione (ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1), Nome char(30) NOT NULL, Nota char(250) NOT NULL, InterventoID integer NOT NULL, PRIMARY KEY (ID));\n" +
            "CREATE TABLE Patologia (Codice char(6) NOT NULL, Nome char(20) NOT NULL, Gravita integer NOT NULL, PRIMARY KEY (Codice));\n" +
            "CREATE TABLE Sofferenza (PazienteID integer NOT NULL, PatologiaCodice char(6) NOT NULL, PRIMARY KEY (PazienteID, PatologiaCodice));\n" +
            "CREATE TABLE Cura (SofferenzaPazienteID integer NOT NULL, SofferenzaPatologiaCodice char(6) NOT NULL, OperazioneID integer NOT NULL, PRIMARY KEY (SofferenzaPazienteID, SofferenzaPatologiaCodice, OperazioneID));\n" +
            "ALTER TABLE Cellulare ADD CONSTRAINT FKCellulare267003 FOREIGN KEY (PazienteID) REFERENCES Paziente (ID);\n" +
            "ALTER TABLE Intervento ADD CONSTRAINT FKIntervento717981 FOREIGN KEY (PazienteID) REFERENCES Paziente (ID);\n" +
            "ALTER TABLE Intervento ADD CONSTRAINT FKIntervento460074 FOREIGN KEY (InfermiereID) REFERENCES Infermiere (ID);\n" +
            "ALTER TABLE Operazione ADD CONSTRAINT FKOperazione802138 FOREIGN KEY (InterventoID) REFERENCES Intervento (ID);\n" +
            "ALTER TABLE Sofferenza ADD CONSTRAINT FKSofferenza752097 FOREIGN KEY (PazienteID) REFERENCES Paziente (ID);\n" +
            "ALTER TABLE Sofferenza ADD CONSTRAINT FKSofferenza655323 FOREIGN KEY (PatologiaCodice) REFERENCES Patologia (Codice);\n" +
            "ALTER TABLE Cura ADD CONSTRAINT FKCura583995 FOREIGN KEY (SofferenzaPazienteID, SofferenzaPatologiaCodice) REFERENCES Sofferenza (PazienteID, PatologiaCodice);\n" +
            "ALTER TABLE Cura ADD CONSTRAINT FKCura401306 FOREIGN KEY (OperazioneID) REFERENCES Operazione (ID) ON DELETE Cascade;";

}
