--CANCELLAZIONE DELLE TABELLE ESISTENTI
DROP VIEW IF EXISTS VISUALIZZAZIONEINTERVENTI;
DROP VIEW IF EXISTS INTERV_INFERM;
DROP VIEW IF EXISTS CONTOINTERVENTI;

DROP TABLE IF EXISTS ATTIVITA;
DROP TABLE IF EXISTS INTERVENTI;
DROP TABLE IF EXISTS PAZIENTI;
DROP TABLE IF EXISTS INFERMIERI;



--CREAZIONE NUOVE TABELLE
CREATE TABLE PAZIENTI
(
	ID IDENTITY,
	NOME VARCHAR(20),
	COGNOME VARCHAR(20),
	DATANASCITA DATE,
	CELLULARE VARCHAR(11)
);


CREATE TABLE INFERMIERI
(
	ID IDENTITY,
	NOME VARCHAR(20),
	COGNOME VARCHAR(20)
);

CREATE TABLE INTERVENTI
(
	ID IDENTITY,
	IDPAZIENTE INTEGER REFERENCES PAZIENTI(ID) ON DELETE CASCADE,
	IDINFERMIERE INTEGER REFERENCES INFERMIERI(ID) ON DELETE CASCADE,
	DATAORA TIMESTAMP,
	CITTA VARCHAR(30),
	CIVICO VARCHAR(30),
	TIPOINTERVENTO VARCHAR(300),
	NOTE VARCHAR(300)
);
	
CREATE TABLE ATTIVITA
(
	IDINTERVENTO INTEGER PRIMARY KEY REFERENCES INTERVENTI(ID) ON DELETE CASCADE,
	DATAORAINIZIO TIMESTAMP,
	DATAORAFINE TIMESTAMP,
	MISURARILEVATA VARCHAR(300),
	LOGFILE VARCHAR(100)
);
--RESET INTERVENTI
DELETE FROM INTERVENTI
ALTER TABLE INTERVENTI ALTER COLUMN ID RESTART WITH 0;

--INSERIMENTO DATI FARLOCCHI
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('GIANNI', 'ROSSI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('ANNA', 'BIANCHI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('DOMENICO', 'ROSSI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('ALBERTO', 'ROSSI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('FABRIZIO', 'VERDI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('GINA', 'ROSSI', '1954-12-24', '3495784632');
INSERT INTO PAZIENTI (NOME, COGNOME, DATANASCITA, CELLULARE) VALUES ('MARGHERITA', 'VERDI', '1954-12-24', '3495784632');

INSERT INTO INFERMIERI (NOME, COGNOME) VALUES ('FRANCESCO', 'COLELLA');
INSERT INTO INFERMIERI (NOME, COGNOME) VALUES ('ANDREA', 'CECI');
INSERT INTO INFERMIERI (NOME, COGNOME) VALUES ('ANTONIO', 'APRILE');
INSERT INTO INFERMIERI (NOME, COGNOME) VALUES ('VITO', 'BIGIO');

INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (1,3,'MOLA DI BARI','VIA FIUME, 90','PRESSIONE','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (2,0,'MOLA DI BARI','VIA GARIBALDI, 90','CAPPELLO','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (3,2,'BARI','PIAZZA MORO, 90','INSULINA','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (4,2,'MOLA DI BARI','VIA TRENTO, 90','ANTIBIOTICO','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (2,3,'MOLA DI BARI','VIA TRIESTE, 90','PRESSIONE','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (6,3,'MOLA DI BARI','VIA TRIPOLI, 90','PRESSIONE','NO', '2012-08-30 10:00:00');
INSERT INTO INTERVENTI (IDPAZIENTE, IDINFERMIERE, CITTA, CIVICO, TIPOINTERVENTO, NOTE, DATAORA) VALUES (0,2,'MOLA DI BARI','VIA FOSCOLO, 90','PRESSIONE','NO', '2012-08-30 10:00:00');
	


--INTERROGAZIONI
--SELEZIONE PIANIFICAZIONE GENERALE
SELECT 
	INTERVENTI.ID,
	PAZIENTI.NOME AS NOME_PAZIENTE,
	PAZIENTI.COGNOME AS COGNOME_PAZIENTE,
	INFERMIERI.NOME AS NOME_INFERMIERE,
	INFERMIERI.COGNOME AS COGNOME_INFERMIERE,
	INTERVENTI.DATAORA,
	INTERVENTI.CITTA,
	INTERVENTI.CIVICO,
	INTERVENTI.NOTE
		
FROM 
	INTERVENTI,PAZIENTI,INFERMIERI 
 
WHERE 
	INTERVENTI.IDINFERMIERE = INFERMIERI.ID
AND
	INTERVENTI.IDPAZIENTE = PAZIENTI.ID


	
	
--QUERY TABELLA PAZIENTI
SELECT * FROM PAZIENTI;

--QUERY TABELLA INFERMIERI
SELECT * FROM INFERMIERI;


--VIEW INFERMIERI CON CONTO INTERVENTI (ANCHE GLI INFERMIERI SENZA INTERVENTI)
CREATE VIEW CONTOINTERVENTI AS (
	SELECT INFERMIERI.ID, COUNT(INTERVENTI.IDINFERMIERE)  AS NUM_INTERV
	FROM INFERMIERI LEFT JOIN INTERVENTI ON INFERMIERI.ID=INTERVENTI.IDINFERMIERE 
	GROUP BY INFERMIERI.ID 
	ORDER BY INFERMIERI.ID
	);

--VIEW TABELLA INFORMAZIONI SU INFERMIERI&INTERVENTI
CREATE VIEW INTERV_INFERM AS (
	SELECT ID,NOME,COGNOME,NUM_INTERV AS NUMINTERVENTI 
	FROM INFERMIERI,CONTOINTERVENTI WHERE INFERMIERI.ID=CONTOINTERVENTI.ID
	);

--VIEW PIANIFICAZIONE GENERALE
CREATE VIEW VISUALIZZAZIONEINTERVENTI AS
(
SELECT
	INTERVENTI.ID,
	INTERVENTI.IDINFERMIERE,
	INFERMIERI.COGNOME AS INFERMIERE,
	INTERVENTI.IDPAZIENTE,
	PAZIENTI.NOME,
	PAZIENTI.COGNOME,
	INTERVENTI.DATAORA,
	INTERVENTI.CITTA,
	INTERVENTI.CIVICO,
	INTERVENTI.NOTE
FROM
	INTERVENTI,INFERMIERI,PAZIENTI
WHERE
	INTERVENTI.IDINFERMIERE=INFERMIERI.ID 
	AND
	INTERVENTI.IDPAZIENTE= PAZIENTI.ID
);	
	
