--CANCELLAZIONE COLONNA CELLULARE PER I PAZIENTI
ALTER TABLE PAZIENTI DROP COLUMN CELLULARE;

--CREAZIONE TABELLA CELLULARI CON FOREIGN KEY PAZIENTE(ID) E NUMERO
CREATE TABLE CELLULARIPAZIENTI(
	PAZIENTE INTEGER REFERENCES PAZIENTI(ID) ON DELETE CASCADE,
	NUMERO VARCHAR(11),
	PRIMARY KEY(PAZIENTE,NUMERO)
);

--RIMOZIONE DELLE VIEW VINCOLATE
DROP VIEW VISUALIZZAZIONEINTERVENTI;

--AGGIUNTA COLONNA CAP ALL'INTERVENTO
ALTER TABLE INTERVENTI ADD COLUMN CAP VARCHAR(5)

--RIMOZIONE COLONNE TIPOINTERVENTO E NOTE DALL'INTERVENTO
ALTER TABLE INTERVENTI DROP COLUMN TIPOINTERVENTO;
ALTER TABLE INTERVENTI DROP COLUMN NOTE;

--RIMOZIONE TIMESTAMP DALL'INTERVENTO ED INSERIMENTO DEI NUOVI ATTRIBUTI DATA, ORAINIZIO E ORAFINE
ALTER TABLE INTERVENTI DROP COLUMN DATAORA;
ALTER TABLE INTERVENTI ADD COLUMN DATAINT DATE;
ALTER TABLE INTERVENTI ADD COLUMN ORAINIZIO TIME;
ALTER TABLE INTERVENTI ADD COLUMN ORAFINE TIME;

--CREAZIONE TABELLA TIPIINTERVENTI
CREATE TABLE TIPIINTERVENTI(
	IDINTERVENTO INTEGER REFERENCES INTERVENTI(ID) ON DELETE CASCADE,
	NOME VARCHAR(301),
	VALORERILEVATO VARCHAR(301),
	TEMPOINTERVENTO TIME,
	NOTE VARCHAR(301),
	PRIMARY KEY(IDINTERVENTO,NOME)
);

--CREAZIONE TABELLA LOG
CREATE TABLE RILEVAZIONI(
	IDINTERVENTO INTEGER REFERENCES INTERVENTI(ID) ON DELETE CASCADE,
	DATARILEVAZIONE DATE,
	ORARILEVAZIONE TIME,
	GPS_LAT DECIMAL,
	GPS_LONG DECIMAL,
	GPS_ALT DECIMAL,
	GPS_ACC DECIMAL,
	ACCEL_X DECIMAL,
	ACCEL_Y DECIMAL,
	ACCEL_Z DECIMAL,
	PRIMARY KEY (IDINTERVENTO,DATARILEVAZIONE,ORARILEVAZIONE)
	);
	
--CREAZIONE VIEW PER PIANIFICAZIONE
--VIEW PIANIFICAZIONE GENERALE

CREATE VIEW VISUALIZZAZIONEINTERVENTI AS
(
SELECT
	INTERVENTI.ID,
	INFERMIERI.COGNOME AS INFERMIERE,
	PAZIENTI.NOME,
	PAZIENTI.COGNOME,
	INTERVENTI.DATAINT,
	INTERVENTI.ORAINIZIO,
	INTERVENTI.ORAFINE,
	INTERVENTI.CITTA,
	INTERVENTI.CIVICO
FROM
	INTERVENTI,INFERMIERI,PAZIENTI
WHERE
	INTERVENTI.IDINFERMIERE=INFERMIERI.ID 
	AND
	INTERVENTI.IDPAZIENTE= PAZIENTI.ID
);		
