/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.boundary;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Francesco
 */
public class DialogoVerifica extends javax.swing.JDialog {

	private static DialogoVerifica window;
	/**
	 * Creates new form DialogoVerifica
	 */
	public DialogoVerifica(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

    private void initComponents() {

        immagineTestataVerifica = new javax.swing.JLabel();
        pannelloTabellaAttivita = new javax.swing.JScrollPane();
        tabellaAttivita = new javax.swing.JTable();
        pannelloTabellaLog = new javax.swing.JScrollPane();
        tabellaLog = new javax.swing.JTable();
        txInfermiere = new javax.swing.JLabel();
        txInfermiere1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        pulsanteAggiornaLista = new javax.swing.JButton();
        cbFileJournaling = new javax.swing.JComboBox();
        pulsanteCarica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabellaAttivita.setRowHeight(25);
        tabellaAttivita.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaAttivita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaAttivitaMouseClicked(evt);
            }
        });
        tabellaAttivita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabellaAttivitaKeyPressed(evt);
            }
        });
        pannelloTabellaAttivita.setViewportView(tabellaAttivita);

        tabellaLog.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaLog.getTableHeader().setReorderingAllowed(false);
        pannelloTabellaLog.setViewportView(tabellaLog);

        txInfermiere.setFont(txInfermiere.getFont().deriveFont(txInfermiere.getFont().getStyle() | java.awt.Font.BOLD, 14));
        txInfermiere.setForeground(new java.awt.Color(255, 255, 255));
        txInfermiere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txInfermiere.setText("Infermere: -");
        txInfermiere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txInfermiere1.setFont(txInfermiere1.getFont().deriveFont(txInfermiere1.getFont().getStyle() | java.awt.Font.BOLD, 14));
        txInfermiere1.setForeground(new java.awt.Color(255, 255, 255));
        txInfermiere1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txInfermiere1.setText("Lista rilevazioni");
        txInfermiere1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        pulsanteAggiornaLista.setText("Aggiorna lista");
        pulsanteAggiornaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiornaListaActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteAggiornaLista);

        jToolBar1.add(cbFileJournaling);

        pulsanteCarica.setText("Carica e verifica");
        pulsanteCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCaricaActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteCarica);

        jLabel1.setText("Cliccare su una singola attivita' per leggere le rilevazioni, premere 'i' per informazioni sull'attività.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloTabellaLog)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(immagineTestataVerifica)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txInfermiere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(txInfermiere1))
                .addGap(0, 40, Short.MAX_VALUE))
            .addComponent(pannelloTabellaAttivita)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(immagineTestataVerifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txInfermiere)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloTabellaAttivita, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txInfermiere1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloTabellaLog, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteAggiornaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAggiornaListaActionPerformed


    }//GEN-LAST:event_pulsanteAggiornaListaActionPerformed

    private void pulsanteCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteCaricaActionPerformed

        
    }//GEN-LAST:event_pulsanteCaricaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void tabellaAttivitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaAttivitaMouseClicked

        
    }//GEN-LAST:event_tabellaAttivitaMouseClicked

    private void tabellaAttivitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabellaAttivitaKeyPressed

        
    }//GEN-LAST:event_tabellaAttivitaKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void start() {

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				window = new DialogoVerifica(new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);
				
			}
		});
	}

	public void stop()
	{
		if (window!=null) window.dispose();
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbFileJournaling;
    private javax.swing.JLabel immagineTestataVerifica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane pannelloTabellaAttivita;
    private javax.swing.JScrollPane pannelloTabellaLog;
    private javax.swing.JButton pulsanteAggiornaLista;
    private javax.swing.JButton pulsanteCarica;
    private javax.swing.JTable tabellaAttivita;
    private javax.swing.JTable tabellaLog;
    private javax.swing.JLabel txInfermiere;
    private javax.swing.JLabel txInfermiere1;
    // End of variables declaration//GEN-END:variables

}
