/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.boundary;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

public class SchermataInterventi extends javax.swing.JDialog implements Boundary {

	public SchermataInterventi(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * Metodo che inizializza il form insieme al costruttore
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        immagineTestataInterventi = new javax.swing.JLabel();
        pannelloDati = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pulsanteConferma = new javax.swing.JButton();
        txCitta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txCivico = new javax.swing.JTextField();
        txData = new javax.swing.JFormattedTextField();
        txCAP = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txPazienteSelezionato = new javax.swing.JFormattedTextField();
        txInfermiereSelezionato = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelIntervento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabellaTipiIntervento = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txOra = new javax.swing.JFormattedTextField();
        pulsanteRimuoviTipo = new javax.swing.JButton();
        txNomePaziente = new javax.swing.JTextField();
        txNomeInfermiere = new javax.swing.JTextField();
        pulsanteAggiungiTipo = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabellaInterventi = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        pulsanteAggiungi = new javax.swing.JButton();
        pulsanteModifica = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        pulsanteEditorPazienti = new javax.swing.JButton();
        pulsanteEditorInfermieri = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaPazienti = new javax.swing.JTable();
        labelPazienti = new javax.swing.JLabel();
        pulsanteImpostaPaziente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabellaInfermieri = new javax.swing.JTable();
        labelInfermieri = new javax.swing.JLabel();
        pulsanteImpostaInfermiere = new javax.swing.JButton();
        labelInterventi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pannelloDati.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Data(gg/mm/aaaa)");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        pulsanteConferma.setText("Conferma inserimento/modifica");
        pulsanteConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteConfermaActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Citta'");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Civico");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txData.setToolTipText("Inserire la data nel formato gg/mm/aaaa (es 23/09/2012)");

        txCAP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000"))));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Ora (hh.mm)");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txPazienteSelezionato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txPazienteSelezionato.setEnabled(false);

        txInfermiereSelezionato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txInfermiereSelezionato.setEnabled(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Paziente");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Infermiere");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        labelIntervento.setFont(labelIntervento.getFont().deriveFont(labelIntervento.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelIntervento.setForeground(new java.awt.Color(255, 255, 255));
        labelIntervento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIntervento.setText("Dati intervento");
        labelIntervento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabellaTipiIntervento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Intervento", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabellaTipiIntervento.setAutoCreateRowSorter(true);
        tabellaTipiIntervento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tabellaTipiIntervento);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("CAP");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setText("EDITOR DEI TIPI DI INTERVENTO (Specificarne almeno uno)");

        txOra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH.mm"))));

        pulsanteRimuoviTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteRimuoviTipoActionPerformed(evt);
            }
        });

        txNomePaziente.setEditable(false);

        txNomeInfermiere.setEditable(false);

        pulsanteAggiungiTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloDatiLayout = new javax.swing.GroupLayout(pannelloDati);
        pannelloDati.setLayout(pannelloDatiLayout);
        pannelloDatiLayout.setHorizontalGroup(
            pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pannelloDatiLayout.createSequentialGroup()
                        .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannelloDatiLayout.createSequentialGroup()
                                .addComponent(txCitta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txCAP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txCivico)))
                    .addGroup(pannelloDatiLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannelloDatiLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txOra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pannelloDatiLayout.createSequentialGroup()
                                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txPazienteSelezionato)
                                    .addComponent(txInfermiereSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNomePaziente)
                                    .addComponent(txNomeInfermiere, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDatiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelIntervento))
                    .addGroup(pannelloDatiLayout.createSequentialGroup()
                        .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pulsanteAggiungiTipo)
                            .addComponent(pulsanteRimuoviTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDatiLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pulsanteConferma)))))
                .addContainerGap())
        );
        pannelloDatiLayout.setVerticalGroup(
            pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDatiLayout.createSequentialGroup()
                .addComponent(labelIntervento)
                .addGap(5, 5, 5)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPazienteSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNomePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txInfermiereSelezionato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNomeInfermiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txOra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCitta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCivico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloDatiLayout.createSequentialGroup()
                        .addComponent(pulsanteAggiungiTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulsanteRimuoviTipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteConferma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabellaInterventi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellaInterventi.setAutoCreateRowSorter(true);
        tabellaInterventi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaInterventi.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tabellaInterventi);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 12));
        jLabel1.setText("Interventi:");
        jToolBar1.add(jLabel1);

        pulsanteAggiungi.setText("Aggiungi");
        pulsanteAggiungi.setFocusable(false);
        pulsanteAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteAggiungi);

        pulsanteModifica.setText("Modifica");
        pulsanteModifica.setFocusable(false);
        pulsanteModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteModificaActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteModifica);
        jToolBar1.add(jSeparator1);

        pulsanteEditorPazienti.setText("Modifica pazienti...");
        pulsanteEditorPazienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEditorPazientiActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteEditorPazienti);

        pulsanteEditorInfermieri.setText("Modifica infermieri...");
        pulsanteEditorInfermieri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEditorInfermieriActionPerformed(evt);
            }
        });
        jToolBar1.add(pulsanteEditorInfermieri);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabellaPazienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellaPazienti.setAutoCreateRowSorter(true);
        tabellaPazienti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaPazienti.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabellaPazienti);

        labelPazienti.setFont(labelPazienti.getFont().deriveFont(labelPazienti.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelPazienti.setForeground(new java.awt.Color(255, 255, 255));
        labelPazienti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPazienti.setText("Pazienti");
        labelPazienti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pulsanteImpostaPaziente.setText("Imposta Paziente selezionato");
        pulsanteImpostaPaziente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteImpostaPaziente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteImpostaPazienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelPazienti)
                .addGap(0, 70, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pulsanteImpostaPaziente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelPazienti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteImpostaPaziente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabellaInfermieri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellaInfermieri.setAutoCreateRowSorter(true);
        tabellaInfermieri.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaInfermieri.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabellaInfermieri);

        labelInfermieri.setFont(labelInfermieri.getFont().deriveFont(labelInfermieri.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelInfermieri.setForeground(new java.awt.Color(255, 255, 255));
        labelInfermieri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfermieri.setText("Infermieri");
        labelInfermieri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pulsanteImpostaInfermiere.setText("Imposta Infermiere selezionato");
        pulsanteImpostaInfermiere.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pulsanteImpostaInfermiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteImpostaInfermiereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelInfermieri)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pulsanteImpostaInfermiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelInfermieri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsanteImpostaInfermiere)
                .addGap(16, 16, 16))
        );

        labelInterventi.setFont(labelInterventi.getFont().deriveFont(labelInterventi.getFont().getStyle() | java.awt.Font.BOLD, 14));
        labelInterventi.setForeground(new java.awt.Color(255, 255, 255));
        labelInterventi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInterventi.setText("Interventi");
        labelInterventi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(immagineTestataInterventi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInterventi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pannelloDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(immagineTestataInterventi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInterventi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pannelloDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>

	private void pulsanteEditorInfermieriActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void pulsanteEditorPazientiActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void pulsanteAggiungiActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void pulsanteModificaActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void formWindowActivated(java.awt.event.WindowEvent evt) {
		// Aggiornamento tabelle al ritorno dai popup
	}

	private void pulsanteImpostaPazienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteImpostaPazienteActionPerformed
		
		
	}//GEN-LAST:event_pulsanteImpostaPazienteActionPerformed

	private void pulsanteImpostaInfermiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteImpostaInfermiereActionPerformed
		
	}//GEN-LAST:event_pulsanteImpostaInfermiereActionPerformed

    private void pulsanteConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteConfermaActionPerformed
        //RECUPERO DATI DAL MODULO
    }//GEN-LAST:event_pulsanteConfermaActionPerformed

    private void pulsanteAggiungiTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAggiungiTipoActionPerformed
        //TODO TEST Chiamata finestra di dialogo

    }//GEN-LAST:event_pulsanteAggiungiTipoActionPerformed

    private void pulsanteRimuoviTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteRimuoviTipoActionPerformed
        
    }//GEN-LAST:event_pulsanteRimuoviTipoActionPerformed


	/**
	 * @param args the command line arguments
	 */
	public static void start() {

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				SchermataInterventi window = new SchermataInterventi(new javax.swing.JFrame(), true);
				Dimension risoluzioneSchermo = Toolkit.getDefaultToolkit().getScreenSize();
				window.setLocation(new Point( (risoluzioneSchermo.width - window.getWidth()) /2, (risoluzioneSchermo.height - window.getHeight()) /2)  );
				window.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel immagineTestataInterventi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelInfermieri;
    private javax.swing.JLabel labelInterventi;
    private javax.swing.JLabel labelIntervento;
    private javax.swing.JLabel labelPazienti;
    private javax.swing.JPanel pannelloDati;
    private javax.swing.JButton pulsanteAggiungi;
    private javax.swing.JButton pulsanteAggiungiTipo;
    private javax.swing.JButton pulsanteConferma;
    private javax.swing.JButton pulsanteEditorInfermieri;
    private javax.swing.JButton pulsanteEditorPazienti;
    private javax.swing.JButton pulsanteImpostaInfermiere;
    private javax.swing.JButton pulsanteImpostaPaziente;
    private javax.swing.JButton pulsanteModifica;
    private javax.swing.JButton pulsanteRimuoviTipo;
    private javax.swing.JTable tabellaInfermieri;
    private javax.swing.JTable tabellaInterventi;
    private javax.swing.JTable tabellaPazienti;
    private javax.swing.JTable tabellaTipiIntervento;
    private javax.swing.JFormattedTextField txCAP;
    private javax.swing.JTextField txCitta;
    private javax.swing.JTextField txCivico;
    private javax.swing.JFormattedTextField txData;
    private javax.swing.JFormattedTextField txInfermiereSelezionato;
    private javax.swing.JTextField txNomeInfermiere;
    private javax.swing.JTextField txNomePaziente;
    private javax.swing.JFormattedTextField txOra;
    private javax.swing.JFormattedTextField txPazienteSelezionato;
    // End of variables declaration//GEN-END:variables
   
    private DefaultTableModel modelloTipiIntervento;

}
